tunnel: e416a082-3967-4708-a1da-f0a86c18a8ac
credentials-file: C:\Users\ADMIN\.cloudflared\e416a082-3967-4708-a1da-f0a86c18a8ac.json
ingress:
  - hostname: hook.bn9.app
    service: http://127.0.0.1:3000
  - hostname: api.bn9.app
    service: http://127.0.0.1:3000
  - service: http_status:404
